# Generated by bin/generate-ipwl
resource "aws_waf_ipset" "internal" {
  name = "${data.template_file.waf.rendered}/internal"

  ip_set_descriptors {
    type  = "IPV4"
    value = "1.232.8.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "101.230.212.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "105.28.97.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "115.249.142.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "115.249.215.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "116.213.80.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "116.6.48.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "119.155.139.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.107.39.250/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.153.148.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.154.29.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.156.78.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.16.24.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.166.105.250/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.168.7.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.171.157.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.172.236.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.172.65.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.181.189.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.193.26.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.196.15.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.197.81.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.197.81.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.227.169.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.23.136.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.25.227.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.29.155.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.30.111.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.33.173.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.36.4.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.40.216.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.41.0.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.41.36.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.45.94.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "12.68.200.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "121.242.9.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "122.56.41.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "138.121.12.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.150/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.158/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.166/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.174/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.182/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.136.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.137.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.138.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.138.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.138.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.150/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.158/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.166/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.174/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.182/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.156.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.157.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.158.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.158.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.158.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.172.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.173.4/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.173.5/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.149/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.150/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.151/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.152/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.153/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.155/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.156/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.181/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.182/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.183/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.184/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.185/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.187/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.175.188/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.178.140/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.180.140/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.30.140/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.30.172/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.33.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.44.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.82.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.85.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.85.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.85.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.90.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.93.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.93.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.107.93.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.10.17/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.10.19/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.18.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.18.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.18.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.18.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.18.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.18.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.149/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.150/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.151/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.152/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.153/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.155/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.156/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.181/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.182/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.183/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.184/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.185/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.187/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "156.109.25.188/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.122.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.122.139/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.14.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.14.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.14.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.14.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.107/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.108/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.150/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.158/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.166/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.171/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.172/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.43/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.44/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.175.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.2.16/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.2.17/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.2.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.2.19/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.2.68/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.2.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.150/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.64/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.243.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.110/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.118/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.126/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.26.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.110/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.118/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.126/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.27.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.41.140/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.41.172/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.110/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.118/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.126/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.198/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.206/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.211/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.212/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.44.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.110/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.118/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.126/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.198/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.206/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.211/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.212/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.45.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.176/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.177/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.179/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.180/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.181/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.182/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.183/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.184/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.185/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.187/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.188/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.189/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.190/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.37/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.4/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.66.52/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.110/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.118/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.126/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.198/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.206/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.211/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.212/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.81.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.82.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.82.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.82.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.9.140/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.9.172/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.102/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.110/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.118/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.126/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.134/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.14/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.142/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.22/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.30/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.38/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.46/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.54/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.6/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.62/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.70/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.78/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.86/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.94/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.97.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.98.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.98.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "157.191.98.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "178.189.21.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "186.96.94.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "186.96.94.243/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "186.96.94.244/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "189.44.6.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "189.56.9.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "190.131.240.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "190.216.184.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "190.241.8.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.213.211.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.240.128.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.240.158.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.240.159.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.240.182.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.240.25.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "193.240.28.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "194.136.109.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "194.209.126.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "195.167.94.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "195.243.183.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "195.29.146.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "195.65.177.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "195.97.35.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "197.149.148.254/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "197.156.117.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "197.211.44.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "197.248.183.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "197.253.30.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "197.254.20.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.199.173.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.232.113.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.31.23.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.39.18.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.48.99.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.54.227.251/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "200.70.23.234/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "201.144.120.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "201.166.138.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "204.245.24.82/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "206.165.166.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "207.243.149.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "207.245.53.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "208.51.23.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "209.58.29.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "210.15.127.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.0.115.234/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.154.125.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.160.157.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.184.181.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.185.124.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.203.68.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.23.249.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.35.100.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "212.92.4.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.14.46.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.208.230.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.246.216.66/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.246.249.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.27.248.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.61.201.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "213.61.75.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "216.13.181.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "217.111.73.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "217.14.231.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "217.243.196.234/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "217.243.203.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "217.89.68.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "217.97.163.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "220.167.79.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "38.108.46.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "38.119.133.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "38.126.169.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "38.142.56.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "38.88.68.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "38.94.153.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.15.113.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.28.113.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.28.114.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.28.114.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.28.144.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.30.169.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.30.170.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.30.94.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.31.153.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.31.221.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.35.204.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.35.243.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.35.86.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.53.197.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.53.20.250/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.58.2.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.58.2.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.58.78.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.59.150.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.59.19.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.59.85.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.79.117.226/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "4.79.15.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "41.0.72.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "41.137.129.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "41.214.128.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "41.73.131.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "46.44.113.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "5.32.70.202/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "50.205.212.122/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "57.191.175.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "60.247.123.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.119.67.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.119.67.202/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.159.183.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.159.183.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.159.95.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.23.99.234/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.231.0.138/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.72.121.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.84.197.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.84.207.202/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.84.216.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "62.96.155.58/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.210.65.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.210.65.91/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.210.65.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.210.67.250/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.211.171.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.212.20.106/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.212.22.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.215.20.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "64.215.23.186/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "65.88.17.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "65.89.101.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "65.89.114.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "65.89.224.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "65.91.169.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "67.78.142.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "67.98.79.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "74.216.217.74/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "78.5.207.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.160.72.114/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.169.111.10/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.169.142.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.169.155.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.169.21.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.169.43.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.179.243.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.171.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.171.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.172.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.172.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.172.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.172.218/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.231.198.178/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.251.161.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.48.251.34/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.76.168.146/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "80.80.17.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "82.166.193.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "83.220.46.202/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "84.14.49.194/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "84.235.51.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "85.223.212.210/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "86.34.165.154/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "86.47.218.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.190.6.162/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.190.6.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.190.7.130/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.190.7.18/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.190.7.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.213.29.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.241.22.234/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "87.241.47.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "88.157.192.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "88.208.88.170/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "88.81.251.98/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "89.175.188.2/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "89.201.173.242/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "89.211.49.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "89.218.74.90/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "90.160.40.42/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "90.161.236.202/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "91.183.64.201/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "93.185.75.26/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "94.20.81.50/32"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "94.56.83.130/32"
  }
}
